# Generated by Django 3.1 on 2020-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0002_jop_jop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='jop_description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
