# Generated by Django 3.1 on 2020-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0006_jop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='jop_image',
            field=models.ImageField(default='', upload_to='jop_image'),
            preserve_default=False,
        ),
    ]
