# Generated by Django 3.1 on 2020-08-11 18:21

from django.db import migrations, models
import jop.models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0008_auto_20200809_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jop',
            name='jop_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=jop.models.image_upload),
        ),
    ]
