# Generated by Django 3.1 on 2020-08-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0009_auto_20200811_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('coverletter', models.TextField()),
            ],
        ),
    ]
