# Generated by Django 3.1 on 2020-08-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0010_applyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyer',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applyer',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='apply_jop', to='jop.jop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applyer',
            name='coverletter',
            field=models.TextField(max_length=500),
        ),
    ]
